"""Embedded word list for diceware-style passphrase generation.

The project does not bundle a dedicated diceware/zxcvbn dependency (see
``key_service``), so this curated list of common, easy-to-transcribe English
words is shipped in-tree. Passphrases are generated by sampling words from this
list with :func:`secrets.choice` (a cryptographically secure RNG).

Entropy per word is ``log2(len(WORDS))``. The generator picks enough words to
exceed a configurable target entropy, so the resulting passphrase strength does
not depend on the exact size of this list — a shorter list simply yields more
words for the same entropy target.
"""

from __future__ import annotations

# A curated list of lowercase, unambiguous words (no homophones, no profanity,
# 4-7 letters). The list length is deliberately well above 256 so that each
# word contributes > 8 bits of entropy.
WORDS: tuple[str, ...] = (
    "anchor", "apple", "arena", "armor", "arrow", "atlas", "autumn", "axis",
    "bacon", "badge", "bagel", "baker", "balance", "banjo", "barrel", "basil",
    "basin", "batch", "beacon", "beagle", "beaver", "bench", "berry", "birch",
    "bishop", "bison", "blanket", "blaze", "block", "bloom", "board", "bobcat",
    "bolt", "bonus", "border", "boulder", "bracket", "branch", "brave", "bread",
    "brick", "bridge", "bright", "broom", "brush", "bubble", "bucket", "buffalo",
    "bunker", "burst", "cabin", "cable", "cactus", "camel", "candle", "canoe",
    "canyon", "carbon", "cargo", "carpet", "carrot", "castle", "cedar", "cement",
    "census", "chalk", "charm", "cheese", "cherry", "chess", "chimney", "cinder",
    "circus", "clamp", "clever", "cliff", "cloak", "clover", "cluster", "cobra",
    "cocoa", "comet", "compass", "copper", "coral", "cottage", "cougar", "cowboy",
    "cradle", "crane", "crater", "crayon", "cricket", "crimson", "crystal", "cube",
    "curtain", "cushion", "cyclone", "daisy", "dancer", "dapper", "dawn", "deacon",
    "delta", "denim", "desert", "diamond", "diesel", "dingo", "dolphin", "domino",
    "donor", "dragon", "drift", "drummer", "dynamo", "eagle", "earth", "easel",
    "ember", "emerald", "engine", "estate", "escort", "exile", "fabric", "falcon",
    "fancy", "feather", "fennel", "ferret", "fiber", "fiddle", "field", "finch",
    "flame", "flask", "fleet", "flint", "florist", "flute", "forest", "fossil",
    "fountain", "fox", "frame", "freckle", "frost", "galaxy", "garlic", "gecko",
    "geyser", "ginger", "glacier", "glider", "glory", "gopher", "granite", "grape",
    "gravel", "grizzly", "grotto", "guitar", "hamlet", "hammer", "harbor", "harvest",
    "hazel", "helmet", "heron", "hickory", "hollow", "honey", "hornet", "hostel",
    "hunter", "husky", "igloo", "indigo", "ingot", "ivory", "jacket", "jaguar",
    "jasmine", "jetty", "jigsaw", "jungle", "juniper", "kayak", "kennel", "kernel",
    "kettle", "keystone", "kingdom", "kitten", "koala", "lagoon", "lantern", "laurel",
    "lava", "ledger", "lemon", "leopard", "lever", "lilac", "linen", "lizard",
    "lobster", "locket", "lotus", "lumber", "lunar", "lynx", "magnet", "mango",
    "maple", "marble", "marina", "marlin", "meadow", "melon", "merit", "meteor",
    "mingle", "minnow", "mirror", "mitten", "moccasin", "monarch", "moose", "mosaic",
    "muffin", "mulberry", "mustang", "nectar", "needle", "nimbus", "noble", "nomad",
    "nugget", "oasis", "ocelot", "olive", "onyx", "opal", "orbit", "orchid",
    "osprey", "otter", "oxide", "oyster", "paddle", "palette", "panda", "pantry",
    "parade", "parcel", "parka", "parrot", "pasture", "peach", "pebble", "pelican",
    "penguin", "pepper", "petal", "pewter", "phantom", "pigeon", "pillar", "pilot",
    "pioneer", "piston", "pixel", "planet", "plasma", "plaza", "plume", "pocket",
    "pollen", "poppy", "portal", "potato", "prairie", "prism", "puffin", "pumpkin",
    "puzzle", "pyramid", "quarry", "quartz", "quiver", "rabbit", "raccoon", "radar",
    "raisin", "rancher", "ranger", "rapid", "raptor", "raven", "razor", "reactor",
    "reef", "relic", "ribbon", "ridge", "ripple", "river", "robin", "rocket",
    "roster", "rubble", "ruby", "rudder", "runner", "saddle", "saffron", "salmon",
    "sandal", "sapphire", "satchel", "scarf", "scout", "sculptor", "seagull", "sequoia",
    "shadow", "shamrock", "shelter", "sherbet", "shovel", "shrimp", "signal", "silver",
    "siren", "sketch", "skipper", "slalom", "sleigh", "slipper", "smoke", "snorkel",
    "socket", "sonar", "sparrow", "sphinx", "spider", "spinach", "spiral", "sprout",
    "squash", "stadium", "stallion", "stencil", "stinger", "stork", "studio", "summit",
    "sundial", "swallow", "sweater", "syrup", "tablet", "tadpole", "talon", "tangle",
    "tapestry", "tavern", "temple", "tenor", "thicket", "thimble", "thistle", "thunder",
    "tiger", "timber", "toaster", "tomato", "topaz", "torch", "tornado", "tractor",
    "trellis", "tripod", "trophy", "trumpet", "tulip", "tundra", "turbine", "turnip",
    "turtle", "tusk", "ukelele", "umbra", "unicorn", "valley", "vanilla", "velvet",
    "vendor", "venom", "vessel", "viola", "violet", "viper", "volcano", "vortex",
    "waffle", "walnut", "walrus", "warden", "wattle", "weasel", "whistle", "willow",
    "window", "winter", "wizard", "wombat", "wonder", "yarrow", "yodel", "zephyr",
    "zigzag", "zinnia", "zircon", "zodiac",
)
