/**
 * RecurringAllowancesPanel — Phase 4 task D10 (G4 + P4-N31).
 *
 * Collapsible panel rendered inside the Staff Detail Overview tab.
 * Lists the staff member's recurring allowance rules and lets admins
 * add, toggle, or remove them. Rules auto-attach to every new draft
 * payslip generated by `payslips.service.generate_for_period`.
 *
 * Per design.md §6.7 + R3.5 + G4:
 *   - On mount: `listRecurringAllowances(staffId)`.
 *   - Table columns: Allowance type, Amount, Unit, Active toggle,
 *     Remove button.
 *   - Amount falls back to `allowance_type.default_amount` when the
 *     rule has no override.
 *   - Unit is read straight from `allowance_type.unit`.
 *   - Toggle calls `updateRecurringAllowance(staffId, ruleId,
 *     { active })`.
 *   - Remove calls `deactivateRecurringAllowance(staffId, ruleId)`
 *     (DELETE endpoint — backend marks `active=false`).
 *   - "+ Add recurring allowance" opens `AddRecurringAllowanceModal`.
 *
 * Conventions:
 *   - Typed client only (`frontend/src/api/payslips.ts`).
 *   - All API responses consumed with `?.` + `?? []` / `?? null`.
 *   - Decimal `amount` arrives as a string; `Number(s)` for display.
 *   - Every effect uses an AbortController.
 *
 * **Validates: Staff Management Phase 4 task D10, R3.5, G4, P4-N31**
 */

import { useCallback, useEffect, useState } from 'react'
import {
  deactivateRecurringAllowance,
  listRecurringAllowances,
  updateRecurringAllowance,
} from '@/api/payslips'
import type { StaffRecurringAllowance } from '@/api/payslips'
import AddRecurringAllowanceModal from './AddRecurringAllowanceModal'

interface Props {
  staffId: string
}

function isAbortError(err: unknown): boolean {
  if (err instanceof DOMException && err.name === 'AbortError') return true
  if (
    typeof err === 'object' &&
    err !== null &&
    'code' in err &&
    (err as { code?: string }).code === 'ERR_CANCELED'
  ) {
    return true
  }
  return false
}

function readErrorMessage(err: unknown): string {
  const detail = (err as { response?: { data?: { detail?: unknown } } })
    ?.response?.data?.detail
  if (typeof detail === 'string') return detail
  if (
    detail &&
    typeof detail === 'object' &&
    'detail' in detail &&
    typeof (detail as { detail?: unknown }).detail === 'string'
  ) {
    return (detail as { detail: string }).detail
  }
  if (err instanceof Error) return err.message
  return 'Action failed.'
}

function formatAmount(value: string | null | undefined): string {
  if (value == null || value === '') return '—'
  const n = Number(value)
  if (!Number.isFinite(n)) return value
  return `$${n.toFixed(2)}`
}

/**
 * Effective amount for a rule: explicit override → allowance type
 * default → unknown (rendered as "—").
 */
function effectiveAmount(rule: StaffRecurringAllowance): string {
  const override = rule?.amount ?? null
  if (override != null && override !== '') return formatAmount(override)
  return formatAmount(rule?.allowance_type?.default_amount ?? null)
}

export default function RecurringAllowancesPanel({ staffId }: Props) {
  const [expanded, setExpanded] = useState<boolean>(true)
  const [items, setItems] = useState<StaffRecurringAllowance[]>([])
  const [loading, setLoading] = useState<boolean>(true)
  const [loadError, setLoadError] = useState<string | null>(null)
  const [refreshTick, setRefreshTick] = useState<number>(0)

  // Per-row busy + error state for toggle / remove.
  const [busyId, setBusyId] = useState<string | null>(null)
  const [rowError, setRowError] = useState<{
    id: string
    message: string
  } | null>(null)

  const [modalOpen, setModalOpen] = useState<boolean>(false)

  const refresh = useCallback(() => setRefreshTick((t) => t + 1), [])

  useEffect(() => {
    if (!staffId) return
    const controller = new AbortController()
    setLoading(true)
    setLoadError(null)
    ;(async () => {
      try {
        const res = await listRecurringAllowances(staffId, controller.signal)
        if (controller.signal.aborted) return
        setItems(res.items ?? [])
      } catch (err) {
        if (isAbortError(err)) return
        setLoadError(readErrorMessage(err))
      } finally {
        if (!controller.signal.aborted) setLoading(false)
      }
    })()
    return () => controller.abort()
  }, [staffId, refreshTick])

  const handleToggleActive = useCallback(
    async (rule: StaffRecurringAllowance) => {
      if (!rule?.id) return
      setBusyId(rule.id)
      setRowError(null)
      try {
        await updateRecurringAllowance(staffId, rule.id, {
          active: !rule.active,
        })
        refresh()
      } catch (err) {
        setRowError({
          id: rule.id,
          message: readErrorMessage(err) || 'Update failed',
        })
      } finally {
        setBusyId(null)
      }
    },
    [staffId, refresh],
  )

  const handleRemove = useCallback(
    async (rule: StaffRecurringAllowance) => {
      if (!rule?.id) return
      setBusyId(rule.id)
      setRowError(null)
      try {
        await deactivateRecurringAllowance(staffId, rule.id)
        refresh()
      } catch (err) {
        setRowError({
          id: rule.id,
          message: readErrorMessage(err) || 'Remove failed',
        })
      } finally {
        setBusyId(null)
      }
    },
    [staffId, refresh],
  )

  const safeItems = items ?? []

  return (
    <div
      className="border border-gray-200 dark:border-gray-700 rounded"
      data-testid="recurring-allowances-panel"
    >
      <button
        type="button"
        className="w-full px-4 py-3 min-h-[44px] text-left text-sm font-medium text-gray-900 dark:text-gray-100 hover:bg-gray-50 dark:hover:bg-gray-800 flex justify-between items-center"
        onClick={() => setExpanded((v) => !v)}
        aria-expanded={expanded}
        data-testid="recurring-allowances-toggle"
      >
        <span>
          Recurring allowances
          {safeItems.length > 0 && (
            <span className="ml-2 text-xs text-gray-500 dark:text-gray-400">
              ({safeItems.length})
            </span>
          )}
        </span>
        <span aria-hidden="true">{expanded ? '−' : '+'}</span>
      </button>

      {expanded && (
        <div className="px-4 py-3 border-t border-gray-200 dark:border-gray-700 space-y-3">
          <div className="flex items-start justify-between gap-3">
            <p className="text-xs text-gray-500 dark:text-gray-400">
              Rules added here auto-attach to every new draft payslip.
              Admins can still override or remove the line on individual
              payslips.
            </p>
            <button
              type="button"
              onClick={() => setModalOpen(true)}
              className="shrink-0 px-3 py-2 min-h-[44px] rounded bg-blue-600 text-white text-sm font-medium hover:bg-blue-700 disabled:opacity-50"
              data-testid="recurring-allowances-add"
            >
              + Add recurring allowance
            </button>
          </div>

          {loading && (
            <p className="text-sm text-gray-500 dark:text-gray-400">Loading…</p>
          )}

          {loadError && !loading && (
            <p
              role="alert"
              className="text-sm text-red-600 dark:text-red-400"
              data-testid="recurring-allowances-error"
            >
              {loadError}
            </p>
          )}

          {!loading && !loadError && safeItems.length === 0 && (
            <p
              className="text-sm text-gray-500 dark:text-gray-400"
              data-testid="recurring-allowances-empty"
            >
              No recurring allowance rules. Click &lsquo;Add&rsquo; to create
              one — it&rsquo;ll auto-attach to every new draft payslip.
            </p>
          )}

          {!loading && !loadError && safeItems.length > 0 && (
            <table
              className="w-full text-sm"
              data-testid="recurring-allowances-table"
            >
              <thead>
                <tr className="text-left text-xs uppercase text-gray-500 dark:text-gray-400">
                  <th className="py-2 pr-2 font-medium">Allowance type</th>
                  <th className="py-2 pr-2 font-medium">Amount</th>
                  <th className="py-2 pr-2 font-medium">Unit</th>
                  <th className="py-2 pr-2 font-medium">Active</th>
                  <th className="py-2 font-medium text-right">Remove</th>
                </tr>
              </thead>
              <tbody>
                {safeItems.map((rule) => {
                  const isBusy = busyId === rule?.id
                  const errMessage =
                    rowError && rowError.id === rule?.id
                      ? rowError.message
                      : null
                  return (
                    <tr
                      key={rule?.id ?? Math.random().toString(36)}
                      className="border-t border-gray-100 dark:border-gray-800"
                      data-testid={`recurring-allowance-row-${rule?.id ?? ''}`}
                    >
                      <td className="py-2 pr-2 text-gray-900 dark:text-gray-100">
                        {rule?.allowance_type?.name ?? '—'}
                      </td>
                      <td className="py-2 pr-2 tabular-nums text-gray-900 dark:text-gray-100">
                        {effectiveAmount(rule)}
                      </td>
                      <td className="py-2 pr-2 text-gray-700 dark:text-gray-300">
                        {rule?.allowance_type?.unit ?? '—'}
                      </td>
                      <td className="py-2 pr-2">
                        <label className="inline-flex min-h-[44px] items-center gap-2">
                          <input
                            type="checkbox"
                            checked={!!rule?.active}
                            onChange={() => handleToggleActive(rule)}
                            disabled={isBusy}
                            data-testid={`recurring-allowance-toggle-${rule?.id ?? ''}`}
                            className="h-5 w-5 rounded border-gray-300"
                          />
                          <span className="text-xs text-gray-600 dark:text-gray-400">
                            {rule?.active ? 'Active' : 'Inactive'}
                          </span>
                        </label>
                        {errMessage && (
                          <p
                            role="alert"
                            className="mt-1 text-xs text-red-600 dark:text-red-400"
                          >
                            {errMessage}
                          </p>
                        )}
                      </td>
                      <td className="py-2 text-right">
                        <button
                          type="button"
                          onClick={() => handleRemove(rule)}
                          disabled={isBusy}
                          className="px-3 py-2 min-h-[44px] rounded border border-red-300 text-sm text-red-700 hover:bg-red-50 disabled:opacity-50 dark:border-red-700 dark:text-red-300 dark:hover:bg-red-900/20"
                          data-testid={`recurring-allowance-remove-${rule?.id ?? ''}`}
                        >
                          Remove
                        </button>
                      </td>
                    </tr>
                  )
                })}
              </tbody>
            </table>
          )}
        </div>
      )}

      <AddRecurringAllowanceModal
        staffId={staffId}
        open={modalOpen}
        onClose={() => setModalOpen(false)}
        onCreated={refresh}
      />
    </div>
  )
}
